### ISSUE TITLE
Create a first version of record linkage for the BHP actors

### ISSUE THREAD

**Issue by gaetanmuck** [geovistory/symogih#1]
The goal here is to find actors (persons) from the BHP database that already exist in Geovistory.

**Comment by gaetanmuck** [comment]
After research, we will use this case as a test for the library Splink

**Comment by gaetanmuck** [comment]
First version of record linkage is done, 
The record linkage itself has been sent to @valamercery and @atterebf for their opinion

The explanation is available [here](https://github.com/geovistory/symogih/blob/master/reports/link-actors-with-geov.html)

**Comment by gaetanmuck** [comment]
We found that there may be needed to first make also a record linkage just for BHP actors themselves, there seems to be duplicated persons there.

**Comment by valamercery** [comment]
The second record linkage seems more relevant:

- Level 1 actors with levensthein distance of 0 are most likely duplicates.
- Level 1 actors with levenshtein of 1 and 2 are most likely duplicates except for those with postulated dates (ex: http://symogih.org/?q=actor-record/61476 and http://symogih.org/?q=actor-record/60507). The latter should be removed from the comparison.
- Level 1 actors with levenshtein of 3 are most likely duplicates except for those with postulated dates and those with a "?" for first name. The latter should be removed from the comparison.
- Level 2 actors with levenshtein distance of 0 are most likely duplicates.
- Level 2 actors with levenshtein distance is equal to or greater than 1 and more are not all duplicates.  As the distance increases, the probability becomes lower.
- Level 3 actors with levenshtein distance of 0 are most likely duplicates except for those with postulated dates, those with a "?" for first name and those with different titles (for instance http://symogih.org/?q=actor-record/28861 and http://symogih.org/?q=actor-record/28860).
- Level 4 actors are probably not duplicates.

**Comment by gaetanmuck** [comment]
Ok, I will then apply those additional rules you mentioned an make a list of actors to import to Geovistory.

**Comment by valamercery** [comment]
@MPica will check the proposals from the last record linkage and report back to us at the end of next week.

**Comment by MPica** [comment]
I have reviewed individually all couples in the table provided. The resulting table is [here](https://github.com/geovistory/symogih/blob/actor-examination/src/record-linkage/persons/bhp-actors-doubles-examined-mp/bhp_entity_recognition_mp.csv).

## Entities to drop

Many turned out to be so poor that they we decided to dump them. Usually, they are linked to 2 informations at the most —when at all. There are no Web/RDF resource linked and no definition of the persons in question. Therefore, often all we have is one date.

| Should be imported | Should __not__ be imported |
| :---------: | :---------: |
| 193 | 197 |

![Diagram of "to be imported" and "to be ignored".](https://github.com/geovistory/symogih/blob/actor-examination/src/record-linkage/persons/bhp-actors-doubles-examined-mp/bhp_acteurs_doublons_import.png?raw=true)

## Couples which complement each other

Some couples turned out to be doubles, with elements of information only present in one or the other. In that case, they were marked as "complémentaires".

## Doubt prevents linkage

Whenever it was not possible to make sure the couple was the same person, they were marked as "doute".

## Triple

Three couples were marked as "triplon", meaning three entities turned out to be the same.

## No firstname

When entities had no first name, they were marked as distinct: we cannot make sure they are the same person.

## Variables in the table

I added the following columns to hold the information:
* **l_equals_r** → holds "oui" if both entities are the same person, "non" if they are distinct or not to be imported.
* **chosen_one_pk** → holds the number of the "master" entity (corresponding to "pk_l" or "pk_r")  if the linkage is approved.
* **please_import** → holds "oui" or "non" according to whether or not the entities should be imported.
* **remarks** → holds more complete information:

| "remarks" value | full instruction | number of couples affected |
| :-----: | :-----: | :-----: |
| "complémentaires" | please import as one entity, but keep all linked information | 43 |
| "données pauvres ou incohérentes" | please do not import either entity | 197 |
| "doute" | please import separately | 31 |
| "prénom inconnu" | please import separately | 17 |
| "triplon louis palandre 63414" | please import all entities as one, keeping all linked information | 3|

![diagram of the numbers to be treated in each mentionned way](https://github.com/geovistory/symogih/blob/actor-examination/src/record-linkage/persons/bhp-actors-doubles-examined-mp/bhp_acteurs_doublons_traitement.png?raw=true)

**Comment by gaetanmuck** [comment]
To translate that into technical specifications:
- imported by mmartinat => `actor.creator` == 28
- no "text_property" => actors that do not appear in at least one of `actor_text_property.fk_creator`

How can I do:
- no other entity linked OR incoherent =>  What does it mean technically?
- no external notice linked ("same as") => Where are they stored?

**Comment by valamercery** [comment]
Many thanks @MPica for your great work! As discussed, I suggest that we apply the constants you gathered only to the corpus of duplicates and not to all the actors.

**Comment by gaetanmuck** [comment]
The work on this subject has been integrated in the code: all identified duplicated has been removed. 

We need to keep in mind:
- Entities that has been merged ("complémentaire") would in Geovistory in the end have 2 URIs link to 2 Symogih actors
- Add the statement in Geovistory between the entities that have a "doute" remark
- Add 3 URIs to the entity "Louis Palandre"
- For remaining rows, when entities has been merged (some of `remarks = empty`), we also need to add 2 URIs in Geovistory.

To keep that in mind, I create a new issue (#4)
